-- ============================================================
-- CrazyNode Supabase setup
-- Run once in Supabase Dashboard -> SQL Editor -> New query
-- Project: https://gkfeplrnllxfroqvpwfw.supabase.co
-- ============================================================

begin;

-- UUID support
create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. Public user profiles linked to Supabase Auth
-- Supabase owns auth.users; never create your own password table.
-- ------------------------------------------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Automatically create/update a profile after Supabase Auth signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', ''),
    case when lower(coalesce(new.email, '')) = 'root@crazynode.in' then 'admin' else 'user' end
  )
  on conflict (id) do update set
    email = excluded.email,
    full_name = excluded.full_name,
    role = excluded.role,
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert or update of email, raw_user_meta_data on auth.users
  for each row execute procedure public.handle_new_user();

-- Backfill profiles for users that already exist, including the admin.
insert into public.profiles (id, email, full_name, role)
select
  id,
  email,
  coalesce(raw_user_meta_data ->> 'full_name', raw_user_meta_data ->> 'name', ''),
  case when lower(coalesce(email, '')) = 'root@crazynode.in' then 'admin' else 'user' end
from auth.users
on conflict (id) do update set
  email = excluded.email,
  full_name = excluded.full_name,
  role = excluded.role,
  updated_at = now();

-- ------------------------------------------------------------
-- 2. Website CMS content
-- All A-to-Z editable settings are JSONB rows identified by key.
-- ------------------------------------------------------------
create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create index if not exists site_settings_updated_at_idx
  on public.site_settings (updated_at desc);

-- Optional audit log for admin edits.
create table if not exists public.site_settings_audit (
  id bigint generated by default as identity primary key,
  setting_key text not null,
  old_value jsonb,
  new_value jsonb,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index if not exists site_settings_audit_key_idx
  on public.site_settings_audit (setting_key, changed_at desc);

create or replace function public.audit_site_setting_change()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.site_settings_audit (setting_key, old_value, new_value, changed_by)
  values (
    coalesce(new.key, old.key),
    case when tg_op = 'INSERT' then null else old.value end,
    case when tg_op = 'DELETE' then null else new.value end,
    auth.uid()
  );
  return coalesce(new, old);
end;
$$;

drop trigger if exists audit_site_settings on public.site_settings;
create trigger audit_site_settings
  after insert or update or delete on public.site_settings
  for each row execute procedure public.audit_site_setting_change();

-- ------------------------------------------------------------
-- 3. Row Level Security
-- ------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.site_settings enable row level security;
alter table public.site_settings_audit enable row level security;

-- Profiles: users see/update only their own profile.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles for select
to authenticated
using (auth.uid() = id or lower(coalesce(auth.jwt() ->> 'email', '')) = 'root@crazynode.in');

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Site content: readable by everyone so the public website works.
drop policy if exists "site_settings_public_read" on public.site_settings;
create policy "site_settings_public_read"
on public.site_settings for select
to anon, authenticated
using (true);

-- Only the authenticated Supabase admin email can create/change/delete content.
drop policy if exists "site_settings_admin_insert" on public.site_settings;
create policy "site_settings_admin_insert"
on public.site_settings for insert
to authenticated
with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'root@crazynode.in');

drop policy if exists "site_settings_admin_update" on public.site_settings;
create policy "site_settings_admin_update"
on public.site_settings for update
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'root@crazynode.in')
with check (lower(coalesce(auth.jwt() ->> 'email', '')) = 'root@crazynode.in');

drop policy if exists "site_settings_admin_delete" on public.site_settings;
create policy "site_settings_admin_delete"
on public.site_settings for delete
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'root@crazynode.in');

-- Audit is visible only to the admin and cannot be manually changed.
drop policy if exists "audit_admin_read" on public.site_settings_audit;
create policy "audit_admin_read"
on public.site_settings_audit for select
to authenticated
using (lower(coalesce(auth.jwt() ->> 'email', '')) = 'root@crazynode.in');

-- ------------------------------------------------------------
-- 4. Initial lightweight settings
-- Plan arrays are automatically supplied by application defaults until
-- first saved in Admin Dashboard, then persisted here in full.
-- ------------------------------------------------------------
insert into public.site_settings (key, value)
values
  ('announcements', '{"enabled":false,"text":"Welcome to CrazyNode","type":"info"}'::jsonb),
  ('site_branding', '{"name":"CrazyNode","email":"root@crazynode.in","logo":"https://i.postimg.cc/fykv1Fgx/1000018451.png"}'::jsonb)
on conflict (key) do nothing;

commit;

-- ============================================================
-- After running:
-- 1. Authentication -> Users: confirm root@crazynode.in exists.
-- 2. Authentication -> URL Configuration:
--    Site URL: https://crazynode.in
--    Redirect URLs:
--      https://crazynode.in/login?confirmed=1
--      https://crazynode.in/update-password
--      http://localhost:3000/login?confirmed=1
--      http://localhost:3000/update-password
-- 3. Never put a service_role key in NEXT_PUBLIC_* variables.
-- 4. Do not store any password in SQL or source code.
-- ============================================================
