import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Service" };

const sections = [
  { title: "Acceptance of Terms", content: "By accessing or using CrazyNode services, you agree to be bound by these Terms of Service. If you do not agree to all the terms and conditions, you may not access or use our services. These terms apply to all visitors, users, and customers who access our hosting platform." },
  { title: "Service Description", content: "CrazyNode provides game server hosting, VPS hosting, dedicated servers, web hosting, and Discord bot hosting services. We reserve the right to modify, suspend, or discontinue any service at any time with reasonable notice. Service specifications, including hardware, bandwidth, and storage allocations, are defined in your service plan." },
  { title: "Acceptable Use Policy", content: "You agree not to use our services for any illegal activities, including but not limited to: distributing malware, hosting phishing sites, engaging in DDoS attacks, storing or sharing copyrighted content without authorization, spam distribution, or any activity that violates local, national, or international law. Violation of this policy may result in immediate service termination without refund." },
  { title: "Payment and Billing", content: "Services are billed in advance on a monthly or annual basis depending on your plan. You agree to provide current, complete, and accurate purchase and account information. Failure to pay invoices within 7 days of the due date may result in service suspension. Services may be terminated after 14 days of non-payment, and data may be permanently deleted after 30 days." },
  { title: "Service Level Agreement", content: "CrazyNode guarantees 99.99% uptime for core infrastructure, excluding scheduled maintenance windows. Scheduled maintenance will be announced at least 24 hours in advance. In the event of uptime falling below our SLA in a calendar month, customers may claim service credits proportional to the downtime experienced." },
  { title: "Data and Backups", content: "While we perform regular automated backups, customers are ultimately responsible for maintaining their own backup copies of critical data. CrazyNode shall not be liable for any data loss resulting from hardware failure, user error, security breaches, or force majeure events. We recommend downloading backups regularly from your control panel." },
  { title: "Intellectual Property", content: "All content, trademarks, logos, and intellectual property on the CrazyNode website and platform are owned by CrazyNode Technologies. You retain all rights to content you upload to your servers. You grant us a limited license to host and transmit your content solely for the purpose of providing services." },
  { title: "Limitation of Liability", content: "To the maximum extent permitted by law, CrazyNode shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities. Our total liability shall not exceed the amount paid by you for services in the twelve months preceding the claim." },
  { title: "Termination", content: "Either party may terminate services at any time. You may cancel through the client area or by contacting support. We reserve the right to suspend or terminate accounts that violate these terms without prior notice. Upon termination, your right to use services ceases immediately, and prepaid fees for the current billing period are non-refundable except as described in our Refund Policy." },
  { title: "Changes to Terms", content: "We may update these Terms of Service from time to time. Material changes will be notified via email or through a prominent notice on our website at least 30 days before taking effect. Continued use of services after changes take effect constitutes acceptance of the updated terms." },
  { title: "Governing Law", content: "These terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these terms or your use of our services shall be subject to the exclusive jurisdiction of the courts of Mumbai, Maharashtra." },
  { title: "Contact Information", content: "For questions about these Terms of Service, please contact us at root@crazynode.in or through our support ticket system in the client area." },
];

export default function TermsPage() {
  return <LegalPage badge="📜 Legal" title="Terms of" highlight="Service" description="The terms and conditions governing your use of CrazyNode hosting services." sections={sections} />;
}
